from pset3 import *

cq = CircularQueue(5)

cq.enqueue(0)
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue(1)
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue(2)
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue(3)
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue(4)
print(cq.items, "      ", cq.head, cq.tail)
cq.dequeue()
print(cq.items, "      ", cq.head, cq.tail)
cq.dequeue()
print(cq.items, "      ", cq.head, cq.tail)
cq.dequeue()
print(cq.items, "      ", cq.head, cq.tail)
cq.dequeue()
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue("r2 0")
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue("r2 1")
print(cq.items, "      ", cq.head, cq.tail)
cq.enqueue("r2 2")
print(cq.items, "      ", cq.head, cq.tail)
